version: "3.7"
services:
  web:
    image: nginx:1.12-alpine
    healthcheck:
      test: ["CMD", "wget", "-qO", "-", "http://localhost:82/"]
      interval: 5s
      timeout: 2s
      retries: 3
      start_period: 15s
    networks:
      - web-net
    ports:
      - 82:80
    deploy:
      replicas: 10
      update_config:
        parallelism: 2
        delay: 10s
      labels:
        app: sample-app
        environment: prod-south
networks:
  web-net:
    driver: overlay